name: Release

on:
  push:
    branches:
      - main
      - dev

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Determine Branch
        run: echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v6.0.2
        id: version

      - name: Create New Format Version
        env:
          PROD_VERSION: "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch}}"
          DEV_VERSION: "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}-${{github.ref_name}}.${{ steps.version.outputs.increment }}"
        run: |
          echo "${{steps.version.outputs.version}}"
          if [[ "${{ env.BRANCH }}" == "main" ]]; then
            echo "NEW_VERSION=${{ env.PROD_VERSION }}" >> $GITHUB_ENV
          else
            echo "NEW_VERSION=${{ env.DEV_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Install packages
        run: |
          sudo apt-get update && \
          sudo apt-get install -yy \
          coreutils procps make cmake \
          build-essential gcc-arm-none-eabi \
          libstdc++-arm-none-eabi-dev libstdc++-arm-none-eabi-newlib \
          libnewlib-arm-none-eabi

      - name: Build binaries
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && \
          cmake --build build

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ env.NEW_VERSION }} -m "Version v${{ env.NEW_VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          tags: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "v${{ env.NEW_VERSION }}"
          generate_release_notes: false
          files: |
            build/reflex-fw.bin
            build/reflex-fw.elf
            build/reflex-fw.hex
